/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;



/**
 *
 * @author PILARES
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcolor = new javax.swing.JLabel();
        btnrojo = new javax.swing.JButton();
        btnverde = new javax.swing.JButton();
        btnazul = new javax.swing.JButton();
        btnamarillo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcolor.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        txtcolor.setForeground(new java.awt.Color(255, 153, 255));
        txtcolor.setText("Colores");

        btnrojo.setText("Rojo");
        btnrojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrojoActionPerformed(evt);
            }
        });

        btnverde.setText("Verde");
        btnverde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverdeActionPerformed(evt);
            }
        });

        btnazul.setText("Azul");
        btnazul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnazulActionPerformed(evt);
            }
        });

        btnamarillo.setText("Amarillo");
        btnamarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnamarilloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnrojo)
                        .addGap(18, 18, 18)
                        .addComponent(btnverde)
                        .addGap(18, 18, 18)
                        .addComponent(btnazul)
                        .addGap(18, 18, 18)
                        .addComponent(btnamarillo)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtcolor)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrojo)
                    .addComponent(btnverde)
                    .addComponent(btnazul)
                    .addComponent(btnamarillo))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrojoActionPerformed
        txtcolor.setText("Rojo");// TODO add your handling code here:
        jPanel1.setBackground(Color.red);
    }//GEN-LAST:event_btnrojoActionPerformed

    private void btnverdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverdeActionPerformed
        txtcolor.setText("Verde");// TODO add your handling code here:
        jPanel1.setBackground(Color.green);
    }//GEN-LAST:event_btnverdeActionPerformed

    private void btnazulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnazulActionPerformed
        txtcolor.setText("Azul");// TODO add your handling code here:
        jPanel1.setBackground(Color.blue);
    }//GEN-LAST:event_btnazulActionPerformed

    private void btnamarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnamarilloActionPerformed
        txtcolor.setText("Amarillo");// TODO add your handling code here:
        jPanel1.setBackground(Color.yellow);
    }//GEN-LAST:event_btnamarilloActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnamarillo;
    private javax.swing.JButton btnazul;
    private javax.swing.JButton btnrojo;
    private javax.swing.JButton btnverde;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtcolor;
    // End of variables declaration//GEN-END:variables
}
